@startuml
actor ReferenceConfig
ReferenceConfig -> ExtensionLoader: getExtensionLoader(Protocol.class).getAdaptiveExtension()
ExtensionLoader -> ExtensionLoader: getExtensionLoader(Class<T> type).getAdaptiveExtension().createAdaptiveExtension()
ExtensionLoader -> ExtensionLoader: getAdaptiveExtensionClass().getExtensionClasses()
ExtensionLoader -> ExtensionLoader: loadExtensionClasses()
note left: 这里会去加载扩展点类META-INF/services/，\nMETA-INF/dubbo/，META-INF/dubbo/internal/
ExtensionLoader -> ExtensionLoader: loadFile()



@enduml